import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { test } from 'node:test'
import { MongoClient } from 'mongodb'
import { GROUP_INDEXES } from '../server/groups.js'
import { migrateGroups } from '../server/groupMigration.js'
import { persistGroupRecord } from '../server/groupTransactions.js'
import { applyUserGroupMove, previewUserGroupMove } from '../server/userGroupMoves.js'

// Deliberately never reads .env or MONGODB_URI. The opt-in URI must point to a
// disposable replica set; the only dropped database is generated by this test.
const uri = process.env.MONGODB_GROUPS_TEST_URI
test('real MongoDB indexes, migration, concurrent transactions and atomic moves', { skip: !uri, timeout: 60000 }, async () => {
  const client = new MongoClient(uri, { serverSelectionTimeoutMS: 10000 })
  const name = `stamjer_groups_test_${randomUUID().replaceAll('-', '')}`
  assert.match(name, /^stamjer_groups_test_[a-f0-9]{32}$/)
  const db = client.db(name)
  let connected = false
  try {
    await client.connect()
    connected = true
    const topology = await db.admin().command({ hello: 1 })
    assert.ok(topology.setName || topology.msg === 'isdbgrid', 'A replica set or sharded deployment is required')
    for (const [collection, definitions] of Object.entries(GROUP_INDEXES)) {
      for (const { keys, options } of definitions) await db.collection(collection).createIndex(keys, options)
    }
    await db.collection('users').createIndex({ id: 1 }, { unique: true })
    await db.collection('users').createIndex({ email: 1 }, { unique: true })
    await db.collection('groups').insertMany([{ id: 'source', slug: 'source', status: 'active', settings: {} }, { id: 'destination', slug: 'destination', status: 'active', settings: {} }])
    await db.collection('users').insertMany([{ id: 1, groupId: 'source', role: 'admin', status: 'active', firstName: 'Member', email: 'member@example.test', password: 'preserved' }, { id: 2, groupId: null, role: 'developer', status: 'inactive', email: 'developer@example.test' }])
    await db.collection('events').insertMany([{ id: 'past', groupId: 'source', start: '2020-01-01', isOpkomst: true, participants: [1], attendance: { 1: false }, opkomstmakerIds: [1] }, { id: 'future', groupId: 'destination', start: '2099-01-01', isOpkomst: true, participants: [] }])
    await db.collection('sessions').insertOne({ sessionId: 'test', userId: 1, revokedAt: null })
    await db.collection('resetCodes').insertOne({ email: 'member@example.test', code: 'preserved' })
    await assert.rejects(db.collection('users').insertOne({ id: 1, email: 'different@example.test' }), { code: 11000 })
    assert.equal((await migrateGroups(db, { apply: true })).applied, true)
    assert.deepEqual((await migrateGroups(db, { apply: true })).updates, { users: 0, events: 0 })
    const actor = await db.collection('users').findOne({ id: 2 })
    const event = await db.collection('events').findOne({ id: 'past' })
    const results = await Promise.allSettled(['First', 'Second'].map(title => persistGroupRecord(client, db, 'events', { ...event, title }, { actor })))
    assert.equal(results.filter(result => result.status === 'fulfilled').length, 1)
    assert.equal(results.find(result => result.status === 'rejected').reason.status, 409)
    assert.equal(await db.collection('auditLogs').countDocuments({ action: 'event-updated' }), 1)
    const current = await db.collection('events').findOne({ id: 'past' })
    const failingDb = { collection: collection => collection === 'auditLogs' ? { async insertOne() { throw new Error('Injected audit failure') } } : db.collection(collection) }
    await assert.rejects(persistGroupRecord(client, failingDb, 'events', { ...current, title: 'Rolled back' }, { actor }), /Injected audit failure/)
    assert.deepEqual(await db.collection('events').findOne({ id: 'past' }), current)
    const options = { userId: 1, destinationGroupId: 'destination', actorId: 2, secret: 'integration-only' }
    const preview = await previewUserGroupMove(client, db, options)
    const moved = await applyUserGroupMove(client, db, { ...options, previewToken: preview.previewToken })
    assert.equal(moved.user.role, 'user')
    assert.equal(moved.user.password, 'preserved')
    assert.equal((await db.collection('userGroupHistory').findOne({ userId: 1 })).streepjes, 1)
    assert.deepEqual((await db.collection('events').findOne({ id: 'past' })).participants, [])
    assert.deepEqual((await db.collection('events').findOne({ id: 'future' })).participants, [1])
    assert.ok((await db.collection('sessions').findOne({ userId: 1 })).revokedAt)
    assert.equal((await db.collection('resetCodes').findOne({ email: 'member@example.test' })).code, 'preserved')
    await assert.rejects(persistGroupRecord(client, db, 'events', { ...current, title: 'Stale' }, { actor }), { status: 409 })
  } finally {
    try { if (connected) await db.dropDatabase() } finally { await client.close() }
  }
})
