/* eslint-disable no-restricted-globals */
/**
 * Service Worker for Stamjer Application
 * Powered by Workbox via vite-plugin-pwa.
 * Handles precaching, offline navigation, API caching and optional background sync.
 */

import { clientsClaim } from 'workbox-core'
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching'
import { registerRoute, NavigationRoute } from 'workbox-routing'
import { CacheFirst, NetworkFirst, StaleWhileRevalidate, NetworkOnly } from 'workbox-strategies'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { ExpirationPlugin } from 'workbox-expiration'

const CACHE_PREFIX = 'stamjer'
const CACHE_VERSION = 'v2'
const API_CACHE_NAME = `${CACHE_PREFIX}-api-${CACHE_VERSION}`
const STATIC_CACHE_NAME = `${CACHE_PREFIX}-static-${CACHE_VERSION}`
const IMAGE_CACHE_NAME = `${CACHE_PREFIX}-images-${CACHE_VERSION}`

// Ensure new service worker activates immediately.
self.skipWaiting()
clientsClaim()

async function clearAllCaches() {
  const keys = await caches.keys()
  const deletions = keys
    .filter((key) => key.startsWith(`${CACHE_PREFIX}-`))
    .map((key) => caches.delete(key))
  await Promise.allSettled(deletions)
}

// Precache all assets generated by the build and cleanup stale ones.
cleanupOutdatedCaches()
// eslint-disable-next-line no-underscore-dangle
precacheAndRoute(self.__WB_MANIFEST, {
  ignoreURLParametersMatching: [/^utm_/, /^fbclid$/]
})

// Offline navigation fallback
const offlineFallback = createHandlerBoundToURL('/index.html')
const navigationHandler = new NetworkFirst({
  cacheName: `${CACHE_PREFIX}-pages-${CACHE_VERSION}`,
  networkTimeoutSeconds: 8,
  plugins: [
    new CacheableResponsePlugin({ statuses: [200] }),
    new ExpirationPlugin({
      maxEntries: 20,
      purgeOnQuotaError: true
    })
  ]
})

registerRoute(
  new NavigationRoute(async (params) => {
    try {
      const response = await navigationHandler.handle(params)
      if (!response) {
        throw new Error('Navigation handler returned undefined response')
      }
      return response
    } catch (error) {
      console.warn('[SW] Falling back to offline shell due to', error)
      return offlineFallback(params)
    }
  })
)

// API requests should always hit the network so the database remains source of truth.
registerRoute(
  ({ url, request }) =>
    request.method === 'GET' && (/^\/api\//.test(url.pathname) || /^\/data\//.test(url.pathname)),
  new NetworkOnly(),
  'GET'
)

// Static assets (JS, CSS, workers) — skip Vercel analytics to avoid noise
registerRoute(
  ({ request, url }) =>
    ['style', 'script', 'worker'].includes(request.destination) &&
    !url.pathname.startsWith('/_vercel/'),
  new StaleWhileRevalidate({
    cacheName: STATIC_CACHE_NAME,
    plugins: [new CacheableResponsePlugin({ statuses: [200] })]
  })
)

// Always bypass SW for Vercel analytics/speed scripts; fail soft if network unavailable
registerRoute(
  ({ url }) => url.pathname.startsWith('/_vercel/'),
  async ({ event }) => {
    try {
      return await fetch(event.request)
    } catch (error) {
      return new Response('', { status: 204 })
    }
  }
)

// Images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: IMAGE_CACHE_NAME,
    plugins: [
      new CacheableResponsePlugin({ statuses: [200] }),
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 7 * 24 * 60 * 60,
        purgeOnQuotaError: true
      })
    ]
  })
)

// Background sync placeholder for queued form submissions.
self.addEventListener('sync', (event) => {
  if (event.tag === 'background-sync-form') {
    event.waitUntil(processQueuedFormSubmissions())
  }
})

self.addEventListener('message', (event) => {
  if (event?.data?.type === 'CLEAR_CACHES') {
    event.waitUntil(clearAllCaches())
  }
})

async function processQueuedFormSubmissions() {
  try {
    const pendingItems = await readPendingFormItems()
    if (pendingItems.length === 0) {
      return
    }

    for (const item of pendingItems) {
      try {
        await fetch(item.url, {
          method: item.method,
          headers: item.headers,
          body: item.body
        })
        await removePendingFormItem(item.id)
      } catch (error) {
        console.error('[SW] Failed to submit queued form item', error)
      }
    }
  } catch (error) {
    console.error('[SW] Background sync error', error)
  }
}

// Placeholder implementations – integrate with IndexedDB as needed.
async function readPendingFormItems() {
  return []
}

async function removePendingFormItem() {
  return Promise.resolve()
}

console.info('[SW] Service worker loaded')
